name:                ModularFibonacci
version:             1.0.2.0
github:              "juergenpf/ModularFibonacci"
license:             BSD3
author:              "Jürgen Pfeifer"
maintainer:          "juergen@familiepfeifer.de"
copyright:           "2019-2024 Jürgen Pfeifer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Excercise to experiment with modular Fibonacci series
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/juergenpf/ModularFibonacci#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ModularFibonacci-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ModularFibonacci

tests:
  ModularFibonacci-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ModularFibonacci
